[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000

[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.production.deploy-redirects]
  from = "/*"
  to = "/"
  status = 200
